### ISSUE TITLE
Enhancement - leverage metamaker to generate levels

### ISSUE THREAD

**Issue by johndpope** [Gummygamer/smmmlevels#1]

**Comment by johndpope** [comment]
should be able to do this quite cleanly using rnn over feature / tile maps.
there's a protobuf here 
https://github.com/Tarnadas/smm-protobuf/blob/master/proto/Tile.proto

**Comment by Gummygamer** [comment]
I'm glad to see some interest around this project, it just happened that
I've stopped working on it at least temporarily. Now maybe I will get back.
It's going to be a hot subject again with Super Mario Maker 2.
Em qua, 20 de fev de 2019 às 08:28, John D. Pope <notifications@github.com>
escreveu:

**Comment by johndpope** [comment]
This library was released the other day / there's a fork with the updates - https://github.com/RoadrunnerWMC/Metamaker/pull/1

You might need this https://www.reddit.com/r/FreeCrackedGames/comments/8ls088/super_mario_maker_wii_u_cemu_rom_mega_link_7252_mb/

**Comment by Gummygamer** [comment]
Found something that helps.
https://medium.com/@ageitgey/machine-learning-is-fun-part-2-a26a10b68df3
Together with metamaker code it seems very feasible to automatically
generate smm levels.

**Comment by johndpope** [comment]
Adding image to add to readme ![si_wiiu_supermariomaker_v01_image1600w](https://user-images.githubusercontent.com/289994/53910421-e956b280-40a7-11e9-936d-23d2508ee5f8.jpg)

**Comment by johndpope** [comment]
<img width="1268" alt="supermario" src="https://user-images.githubusercontent.com/289994/53910669-81549c00-40a8-11e9-91dc-f4d8e0960dac.png">

**Comment by Gummygamer** [comment]
Now I actually made it minimally work, but the real AI part is separate code.

**Comment by Erickira3** [comment]
I've committed and pushed some minimal ML part. While it can do training and prediction more work have to be done to find the right ML architecture that will give the best level creation possible.
I'll continue to work on it for now.

**Comment by Gummygamer** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Governo Federal - Ministério da
Economia: Criação de políticas de apoio econômico ao Cirurgião Dentista
brasileiro" e queria saber se você pode ajudar assinando também.

A nossa meta é conseguir 75.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/ZpMS7F7hdN

Obrigado/a!
André
