### ISSUE TITLE
Investigate downloading prebuilt levels en masse for training

### ISSUE THREAD

**Issue by johndpope** [Gummygamer/smmmlevels#3]
https://github.com/tachyo/SMMData/issues/5

**Comment by Erickira3** [comment]
The level used for training the models are levels from SMMDB. While we use the cemu navigator to download them it may be possible to create a script that will download them without using the said emulator. I'll put it on my todo list.
For the level, we are predicting as for now there is no plan to expose them on the internet as our prediction is not that reliable yet. Maybe when we can predict a good doable stage it will be done.
